# Generated by Django 2.0.4 on 2018-05-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='titulo',
            new_name='nombre',
        ),
    ]
